// * This Java source file was generated by the Gradle 'init' task.
package lab01;
import java.util.Random;
import java.time.LocalDateTime ;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;


public class App {


    // pluralize method
    public static String pluralize (String word , int count) {
        if (count > 1 || count == 0)
        return word+"s";

        return word;

    }

    // flipNHeads method

   public static void  flipNHeads(int n){
        int count =0;
        int countHowManyFlipsItTakes = 0;
        Random random = new Random();
        float random_number= random.nextFloat();
       System.out.println(random_number);
        while (count != n ){

            if (random.nextFloat() > 0.5){
                ++count;
                System.out.println("heads");
            }
            else {
                count=0;
                System.out.println("tails");
            }
            ++countHowManyFlipsItTakes;
            }


       System.out.println( "It took "+ countHowManyFlipsItTakes +" flip to flip "+ n  + " heads in a row.");

        }

    // clock  method

    public static   String clock(){

            LocalDateTime now = LocalDateTime.now();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("HH:mm:ss");
            String formatDateTime = now.format(format);

            return formatDateTime;
        }

// pluralize method

    public static void main(String[] args) {
        //   pluralize invocation
        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");

       // flipNHeads invocation

        flipNHeads(2);


        // clock invocation

        Timer timer = new Timer(); //define a timer
        timer.schedule(new TimerTask() { // schedule it and overide it
            @Override
            public void run() { // run the timer against  the clock method
                System.out.println( clock());
            }
        }, 0, 1000);

    }
}
