/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;



import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static String javaScriptLinter(String filePath) {
        System.out.println(filePath);
        Path path = Paths.get(App.class.getResource("/"+filePath).toURI()); // getting the file path
        BufferedReader reader  = null; //define the reader
        String missingSemicolon="";
        int currentLine = 1;
        try {
            reader = Files.newBufferedReader(path); // assign the reader with the file path
            String line = reader.readLine();

            while(line != null){
                if(     line.contains("if") ||
                        line.contains("else")||
                        line.contains("{") ||
                        line.contains("}")||
                        line.contains("//")  ||
                        line.contains(";")  ||
                        line.length() ==0 &&
                                !line.contains("return")  ) {
                 // System.out.println("no errors found");
                }

                else {
                   // System.out.println(line);
                    missingSemicolon+="Line "+currentLine+": Missing semicolon.\n";
                        //    System.out.println( "Line "+currentLine+": Missing semicolon.");
                }
                currentLine++;
                line = reader.readLine();
            }
        } catch (IOException ex){
            ex.printStackTrace();
        } finally {
            if(reader != null) {
                try {
                    reader.close();
                } catch(IOException e){
                    System.out.println("an error occurred while closing the file");
                }
            }
        }

        return missingSemicolon;
    }

    public static void main(String[] args) {

        System.out.println(App.javaScriptLinter("gates.js"));
        System.out.println(App.javaScriptLinter("gatesWithNoErrors.js"));
        System.out.println(App.javaScriptLinter("gatesWithOneError.js"));
        System.out.println(App.javaScriptLinter("gatesWithfewError.js"));
        System.out.println(App.javaScriptLinter("gatesWithManyErrors.js"));
    }

}
