/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testJavaScriptLinter() {

        System.out.println(App.javaScriptLinter("gates.js"));
        System.out.println(App.javaScriptLinter("gatesWithNoErrors.js"));
        System.out.println(App.javaScriptLinter("gatesWithOneError.js"));
        System.out.println(App.javaScriptLinter("gatesWithfewError.js"));
        System.out.println(App.javaScriptLinter("gatesWithManyErrors.js"));
        assertEquals("",App.javaScriptLinter("gatesWithNoErrors.js"));
        assertEquals("Line 3: Missing semicolon.",App.javaScriptLinter("gatesWithOneError.js"));
        assertEquals("Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 11: Missing semicolon.\n" +
                "Line 13: Missing semicolon.\n" +
                "Line 20: Missing semicolon.\n" +
                "Line 22: Missing semicolon.\n"
                ,App.javaScriptLinter("gatesWithManyErrors.js"));
    }
}
